import { motion } from 'motion/react'
import { Emphasis } from '../components/Emphasis'
import { SectionLabel } from '../components/SectionLabel'
import { SpecTable } from '../components/SpecTable'
import { Counter } from '../components/Counter'
import { AsciiArrow } from '../components/AsciiArrow'
import { MisCommitChart } from '../components/MisCommitChart'
import { MetricBadge } from '../components/MetricBadge'
import { EXPERIMENT_RESULTS } from '../data/experimentResults'

/**
 * Impact and validation. One measured simulation result up front, then the
 * projected human-study KPIs and the rollout. Every simulation number is read
 * from the generated experiment module (src/case-study/data/experimentResults.ts),
 * regenerated by `npm run experiment`. Nothing quantitative here is hand-typed.
 */
export function Impact() {
  // The copy references specific cells; pull them by id so every number below
  // is an expression off the executed data, never a literal.
  const cell = (scenarioId: string, tierId: string) => {
    const c = EXPERIMENT_RESULTS.cells.find(
      (x) => x.scenarioId === scenarioId && x.tierId === tierId,
    )
    if (!c) throw new Error(`missing experiment cell ${scenarioId}/${tierId}`)
    return c
  }
  const tab = cell('tab-contest', 'essential')
  const dock = cell('dock-contest', 'essential')
  const pct = (n: number) => `${(n * 100).toFixed(1)}%`
  const pts = (n: number) => Math.round(n * 100)
  const num2 = (n: number | null) => (n === null ? 'n/a' : n.toFixed(2))

  return (
    <section className="cs-section" id="impact" style={{ background: 'var(--cs-bg-tint)' }}>
      <div className="cs-container">
        <motion.div
          initial={{ opacity: 0, y: 24 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true, amount: 0.3 }}
          transition={{ duration: 0.7, ease: [0.2, 0.8, 0.3, 1.0] }}
        >
          <AsciiArrow length={5} />
          <SectionLabel>08 &middot; impact</SectionLabel>
          <h2 className="cs-h2">
            <Emphasis>measurable</Emphasis> on day one.
          </h2>
          <p className="cs-body">
            every claim in this design is set up to be tested. one of them already
            is: the gesture engine ships with a headless replay that drives its
            real hit-test over a seeded hand-tremor model, so the core claim is
            measured, not asserted. the rest are baselines and targets a real
            study would confirm or kill.
          </p>
        </motion.div>

        {/* Headline stats. The third is a measured simulation result; the others
            are clearly tagged as estimates or projected targets. */}
        <div className="cs-grid cs-grid-4" style={{ marginTop: 64 }}>
          <motion.div
            className="cs-stat"
            initial={{ opacity: 0, y: 16 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true, amount: 0.3 }}
            transition={{ duration: 0.6 }}
          >
            <div className="cs-stat-value">
              <Counter value={20} suffix="M+" />
            </div>
            <div className="cs-stat-label">
              US adults with significant motor impairment, counted once across
              overlapping conditions. <MetricBadge kind="estimate" />
            </div>
          </motion.div>
          <motion.div
            className="cs-stat"
            initial={{ opacity: 0, y: 16 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true, amount: 0.3 }}
            transition={{ duration: 0.6, delay: 0.08 }}
          >
            <div className="cs-stat-value">
              <Counter value={230} suffix="M" />
            </div>
            <div className="cs-stat-label">
              US licensed drivers. curb-cut beneficiaries of the same affordances.
              <MetricBadge kind="estimate" />
            </div>
          </motion.div>
          <motion.div
            className="cs-stat"
            initial={{ opacity: 0, y: 16 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true, amount: 0.3 }}
            transition={{ duration: 0.6, delay: 0.16 }}
          >
            <div className="cs-stat-value">
              <Counter value={pts(tab.absoluteRiskReduction)} suffix=" pts" />
            </div>
            <div className="cs-stat-label">
              simulated drop in first-try mis-commits at the tab boundary, region
              gating on vs off, essential tremor. <MetricBadge kind="measured" />
            </div>
          </motion.div>
          <motion.div
            className="cs-stat"
            initial={{ opacity: 0, y: 16 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true, amount: 0.3 }}
            transition={{ duration: 0.6, delay: 0.24 }}
          >
            <div className="cs-stat-value">
              <Counter value={85} suffix="%" />
            </div>
            <div className="cs-stat-label">
              target first-try task completion for motor-constrained users,
              estimated baseline 45%. <MetricBadge kind="projected" />
            </div>
          </motion.div>
        </div>

        {/* The one measured anchor, wired to executed simulation output. */}
        <motion.div
          style={{ marginTop: 80 }}
          initial={{ opacity: 0, y: 16 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true, amount: 0.2 }}
          transition={{ duration: 0.7, ease: [0.2, 0.8, 0.3, 1.0] }}
        >
          <h3 className="cs-h3" style={{ display: 'flex', alignItems: 'center', flexWrap: 'wrap', gap: 4 }}>
            what the simulation already shows <MetricBadge kind="measured" />
          </h3>
          <p className="cs-body">
            i drove the prototype's actual hit-test over a seeded hand-tremor
            model, region gating on versus off, the same {EXPERIMENT_RESULTS.seedCount}{' '}
            seeds for both arms, across three tremor profiles (physiological,
            essential, parkinsonian) and two contested layouts: a finger caught
            in the gap between the tabs and the first contact row, and a finger
            caught between the dock rail and the content.
          </p>
          <p className="cs-body">
            in the tab-vs-content contest, the case this whole redesign is about,
            gating took first-try mis-commits from {pct(tab.offRate)} down to 0 of{' '}
            {tab.n} (95 percent upper bound {pct(tab.onWilson.hi)}). in the harder
            dock contest, where the finger physically crosses into the dock rail,
            it cut them from {pct(dock.offRate)} to {pct(dock.onRate)}, a risk
            ratio of {num2(dock.riskRatio)} (95 percent CI{' '}
            {dock.bootstrapRiskRatio ? `${num2(dock.bootstrapRiskRatio.lo)} to ${num2(dock.bootstrapRiskRatio.hi)}` : 'n/a'}).
            gating reduced mis-commits in every one of the six conditions.
          </p>

          <div className="cs-grid cs-grid-2" style={{ marginTop: 40, gap: 48 }}>
            <figure className="cs-chart-figure">
              <MisCommitChart data={EXPERIMENT_RESULTS} scenarioId="tab-contest" />
            </figure>
            <figure className="cs-chart-figure">
              <MisCommitChart data={EXPERIMENT_RESULTS} scenarioId="dock-contest" />
            </figure>
          </div>

          <p className="cs-body" style={{ marginTop: 40 }}>
            two honest notes. this is a simulation of the geometry and the
            hit-test, not a human trial: it shows the mechanism resolves the
            intended target under a modeled tremor, not that a real driver
            finishes the call. and the tremor profiles are not a severity ladder.
            a small tremor often mis-commits more than a large one, because a
            small wobble keeps the finger pinned on the contested edge while a
            big one overshoots past it onto the right row.
          </p>
          <p className="cs-body">
            every number here regenerates from one command,{' '}
            <code className="spec-value">npm run experiment</code>, and the replay
            drives the exact hit-test the live prototype ships. the baselines and
            targets below stay projections for a study not yet run.
          </p>
        </motion.div>

        {/* KPI tables. Projected, not measured. */}
        <div className="cs-grid cs-grid-2" style={{ marginTop: 80, gap: 48 }}>
          <motion.div
            initial={{ opacity: 0, y: 16 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true, amount: 0.3 }}
            transition={{ duration: 0.6 }}
          >
            <h3 className="cs-h3" style={{ display: 'flex', alignItems: 'center', flexWrap: 'wrap', gap: 4 }}>
              primary KPIs <MetricBadge kind="projected" />
            </h3>
            <SpecTable
              caption="estimated baseline -> target"
              rows={[
                { label: 'Eyes-off-road time per task',  value: '~3.5s -> <= 2.5s' },
                { label: 'Time-to-call from home',       value: '~7s -> <= 4.5s' },
                { label: 'Motor task completion rate',   value: '~45% -> >= 85%' },
                { label: 'Mis-action rate',              value: '~8% -> <= 3%' },
                { label: 'Subjective fatigue (Borg-CR10)', value: '~4 -> <= 3' },
              ]}
            />
          </motion.div>

          <motion.div
            initial={{ opacity: 0, y: 16 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true, amount: 0.3 }}
            transition={{ duration: 0.6, delay: 0.08 }}
          >
            <h3 className="cs-h3">latency targets</h3>
            <SpecTable
              rows={[
                { label: 'Tap-to-visual (orb)',         value: '<= 100ms' },
                { label: 'Magnifier follow (drag)',     value: '<= 50ms' },
                { label: 'Cold-start to interactive',   value: '<= 400ms' },
                { label: 'Frame rate (gesture)',        value: '60fps' },
                { label: 'Reduce Motion path',          value: 'crossfade swap' },
              ]}
            />
          </motion.div>
        </div>

        {/* Rollout */}
        <motion.div
          style={{ marginTop: 80 }}
          initial={{ opacity: 0, y: 16 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true, amount: 0.3 }}
          transition={{ duration: 0.6 }}
        >
          <h3 className="cs-h3">phased rollout</h3>
          <div className="cs-grid cs-grid-2">
            <div className="cs-card">
              <div className="cs-kicker">phase 1 &middot; phone deep build</div>
              <p style={{ fontSize: 'var(--text-sm-plus)', lineHeight: 1.55, margin: 0, color: 'var(--cs-text)' }}>
                master orb ships as system chrome. the Phone app adopts the
                magnifier first. the Contacts tab disappears from the driving
                state instead of redirecting. a radial dialer replaces the
                keypad in parked-only state. opt-in for general users, default-on
                for paired-iPhone AssistiveTouch users.
              </p>
            </div>
            <div className="cs-card">
              <div className="cs-kicker">phase 2 &middot; system-wide</div>
              <p style={{ fontSize: 'var(--text-sm-plus)', lineHeight: 1.55, margin: 0, color: 'var(--cs-text)' }}>
                Maps adopts the magnifier for point-of-interest pins and the
                quick-controls strip. Music adopts it for queue selection and
                scrub-bar drift. the third-party API <code className="spec-value">CPMagnifiableTarget</code> ships
                at the following WWDC. the cellular widget-grid layout kicks off
                as the second case study in the series.
              </p>
            </div>
          </div>
        </motion.div>

        {/* Generalization: the primitive is about coarse pointing, not cars.
            Design arguments, not measured claims, so no badges here. */}
        <motion.div
          style={{ marginTop: 80 }}
          initial={{ opacity: 0, y: 16 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true, amount: 0.2 }}
          transition={{ duration: 0.6 }}
        >
          <h3 className="cs-h3">where the primitive travels</h3>
          <p className="cs-body">
            this part is argument, not measurement. none of this is really a
            car feature: it is an answer to coarse pointing, any situation
            where the instrument doing the pointing is less precise than the
            target it is aimed at. the car is the harshest version of that
            problem, which is why the design started there. but the same
            physics shows up on very different screens.
          </p>
          <div className="cs-grid cs-grid-2" style={{ marginTop: 40 }}>
            <div style={{ paddingTop: 18, borderTop: '2px solid var(--cs-text)' }}>
              <div className="cs-kicker" style={{ marginBottom: 10 }}>reach 01</div>
              <h4 style={{ fontSize: 18, fontWeight: 600, margin: '0 0 12px', letterSpacing: '-0.01em' }}>
                a tv, ten feet away
              </h4>
              <p style={{ fontSize: 'var(--text-sm-plus)', color: 'var(--cs-text-2)', margin: 0, lineHeight: 1.55 }}>
                a d-pad already solves coarse pointing by removing it: discrete
                hops on a layout graph, no position to lose. the interesting
                case is the pointer remote, gyro wands and free-cursor input,
                where position turns continuous and wobbly again. that is this
                exact problem ten feet back, and the same lock radius,
                hysteresis, and commit-on-lift apply.
              </p>
            </div>
            <div style={{ paddingTop: 18, borderTop: '2px solid var(--cs-text)' }}>
              <div className="cs-kicker" style={{ marginBottom: 10 }}>reach 02</div>
              <h4 style={{ fontSize: 18, fontWeight: 600, margin: '0 0 12px', letterSpacing: '-0.01em' }}>
                small screens
              </h4>
              <p style={{ fontSize: 'var(--text-sm-plus)', color: 'var(--cs-text-2)', margin: 0, lineHeight: 1.55 }}>
                on a watch, the finger is bigger than the thing it is hunting. a
                lock radius plus commit-on-lift beats demanding pixel-perfect
                taps from a fingertip that covers the whole button.
              </p>
            </div>
            <div style={{ paddingTop: 18, borderTop: '2px solid var(--cs-text)' }}>
              <div className="cs-kicker" style={{ marginBottom: 10 }}>reach 03</div>
              <h4 style={{ fontSize: 18, fontWeight: 600, margin: '0 0 12px', letterSpacing: '-0.01em' }}>
                spatial interfaces
              </h4>
              <p style={{ fontSize: 'var(--text-sm-plus)', color: 'var(--cs-text-2)', margin: 0, lineHeight: 1.55 }}>
                hand-tracked pinch jitters for everyone, not just people with a
                tremor. gaze plus gating is the same design wearing different
                hardware.
              </p>
            </div>
            <div style={{ paddingTop: 18, borderTop: '2px solid var(--cs-text)' }}>
              <div className="cs-kicker" style={{ marginBottom: 10 }}>reach 04</div>
              <h4 style={{ fontSize: 18, fontWeight: 600, margin: '0 0 12px', letterSpacing: '-0.01em' }}>
                model-driven interfaces
              </h4>
              <p style={{ fontSize: 'var(--text-sm-plus)', color: 'var(--cs-text-2)', margin: 0, lineHeight: 1.55 }}>
                when a model resolves what you meant, the gesture only has to be
                roughly right. intent resolution narrows what you are aiming at;
                the same deterministic gate still decides when it fires.
              </p>
            </div>
          </div>
        </motion.div>
      </div>
    </section>
  )
}
